title: 0xmchadha's Blog
description: A personal blog
author: 0xmchadha
email:

# Build settings
theme: jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# URL settings
url: "https://0xmchadha.github.io"
baseurl: ""

# Theme settings
class: dark  # Options: dark, light
style: dark  # Options: dark, light, hacker
header:
  pages:
    - title: Home
      url: /
    - title: About
      url: /about/
    - title: Posts
      url: /posts/

footer:
  social:
    github: 0xmchadha

# Pagination
paginate: 5

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
